export class AnimalShapeRenderer {
  static create(scene, fighter, flip = false, scale = 1) {
    const dir = flip ? -1 : 1;
    const c = fighter.color;
    const dark = 0x09070d;
    const parts = [];
    parts.push(scene.add.ellipse(0, 42 * scale, 112 * scale, 18 * scale, 0x000000, 0.28));
    switch (fighter.id) {
      case 'gorilla': parts.push(...this.createGorilla(scene, dir, scale, c, dark)); break;
      case 'tiger': parts.push(...this.createTiger(scene, dir, scale, c, dark)); break;
      case 'snake': parts.push(...this.createSnake(scene, dir, scale, c, dark)); break;
      case 'rhino': parts.push(...this.createRhino(scene, dir, scale, c, dark)); break;
      case 'crocodile': parts.push(...this.createCrocodile(scene, dir, scale, c, dark)); break;
      case 'eagle': parts.push(...this.createEagle(scene, dir, scale, c, dark)); break;
      default:
        parts.push(scene.add.ellipse(0, 0, 76 * scale, 48 * scale, c).setStrokeStyle(3, dark));
        parts.push(scene.add.circle(42 * dir * scale, -10 * scale, 24 * scale, c).setStrokeStyle(3, dark));
        parts.push(scene.add.circle(49 * dir * scale, -17 * scale, 4 * scale, 0xffffff));
    }
    return parts;
  }
  static createGorilla(scene, dir, scale, c, dark) { return [scene.add.ellipse(-6 * dir * scale, 1 * scale, 84 * scale, 74 * scale, c).setStrokeStyle(3, dark),scene.add.ellipse(22 * dir * scale, -16 * scale, 56 * scale, 50 * scale, c).setStrokeStyle(3, dark),scene.add.ellipse(-38 * dir * scale, 22 * scale, 32 * scale, 62 * scale, 0x4f4844).setStrokeStyle(3, dark).setRotation(0.18 * dir),scene.add.ellipse(-8 * dir * scale, 26 * scale, 28 * scale, 56 * scale, 0x564f4a).setStrokeStyle(3, dark).setRotation(-0.12 * dir),scene.add.ellipse(24 * dir * scale, -8 * scale, 30 * scale, 24 * scale, 0x2f2a28).setStrokeStyle(2, dark),scene.add.circle(34 * dir * scale, -17 * scale, 3.8 * scale, 0xffffff),scene.add.ellipse(-3 * dir * scale, -3 * scale, 36 * scale, 26 * scale, 0x6d6763, 0.55)]; }
  static createTiger(scene, dir, scale, c, dark) { const parts = [scene.add.ellipse(-8 * dir * scale, 6 * scale, 112 * scale, 42 * scale, c).setStrokeStyle(3, dark),scene.add.circle(50 * dir * scale, -8 * scale, 22 * scale, c).setStrokeStyle(3, dark),scene.add.triangle(43 * dir * scale, -29 * scale, -8 * dir, 10, 0, -12, 12 * dir, 10, c).setStrokeStyle(2, dark),scene.add.triangle(58 * dir * scale, -27 * scale, -8 * dir, 10, 0, -12, 12 * dir, 10, c).setStrokeStyle(2, dark),scene.add.ellipse(-76 * dir * scale, -1 * scale, 64 * scale, 9 * scale, c).setStrokeStyle(3, dark).setRotation(-0.4 * dir),scene.add.rectangle(-26 * dir * scale, 24 * scale, 9 * scale, 16 * scale, 0x3a2211).setStrokeStyle(2, dark),scene.add.rectangle(0 * dir * scale, 24 * scale, 9 * scale, 16 * scale, 0x3a2211).setStrokeStyle(2, dark),scene.add.rectangle(25 * dir * scale, 22 * scale, 8 * scale, 15 * scale, 0x3a2211).setStrokeStyle(2, dark),scene.add.circle(56 * dir * scale, -14 * scale, 3.8 * scale, 0xffffff)]; [-28, -10, 8, 26].forEach((x) => parts.push(scene.add.rectangle(x * dir * scale, 2 * scale, 7 * scale, 34 * scale, 0x2c160a).setRotation(0.1 * dir))); return parts; }
  static createSnake(scene, dir, scale, c, dark) { const parts = []; [{ x: -40, y: 14, w: 42, h: 24 },{ x: -18, y: 8, w: 46, h: 24 },{ x: 7, y: 12, w: 48, h: 24 },{ x: 28, y: 4, w: 38, h: 22 }].forEach((s, i) => parts.push(scene.add.ellipse(s.x * dir * scale, s.y * scale, s.w * scale, s.h * scale, c).setStrokeStyle(3, dark).setRotation((i % 2 === 0 ? 0.09 : -0.09) * dir))); parts.push(scene.add.ellipse(50 * dir * scale, -8 * scale, 30 * scale, 26 * scale, c).setStrokeStyle(3, dark)); parts.push(scene.add.circle(57 * dir * scale, -12 * scale, 3.7 * scale, 0xffffff)); parts.push(scene.add.triangle(66 * dir * scale, -6 * scale, 0, 0, 14 * dir, -4, 14 * dir, 4, 0xa6e06e)); parts.push(scene.add.rectangle(71 * dir * scale, -6 * scale, 12 * scale, 2 * scale, 0xe06f80)); return parts; }
  static createRhino(scene, dir, scale, c, dark) { return [scene.add.ellipse(-10 * dir * scale, 8 * scale, 104 * scale, 62 * scale, c).setStrokeStyle(3, dark),scene.add.ellipse(36 * dir * scale, -10 * scale, 56 * scale, 44 * scale, c).setStrokeStyle(3, dark),scene.add.ellipse(-24 * dir * scale, -8 * scale, 52 * scale, 30 * scale, 0x848484, 0.45),scene.add.triangle(72 * dir * scale, -16 * scale, 0, 8, 0, -8, 34 * dir, -1, 0xded7be).setStrokeStyle(2, dark),scene.add.rectangle(-34 * dir * scale, 30 * scale, 14 * scale, 20 * scale, 0x6b6b6b).setStrokeStyle(2, dark),scene.add.rectangle(-8 * dir * scale, 32 * scale, 14 * scale, 20 * scale, 0x6b6b6b).setStrokeStyle(2, dark),scene.add.rectangle(20 * dir * scale, 30 * scale, 14 * scale, 20 * scale, 0x6b6b6b).setStrokeStyle(2, dark),scene.add.circle(50 * dir * scale, -18 * scale, 3.8 * scale, 0xffffff)]; }
  static createCrocodile(scene, dir, scale, c, dark) { const parts = [scene.add.ellipse(-12 * dir * scale, 8 * scale, 112 * scale, 32 * scale, c).setStrokeStyle(3, dark),scene.add.rectangle(52 * dir * scale, 2 * scale, 64 * scale, 18 * scale, 0x365e33).setStrokeStyle(3, dark),scene.add.triangle(-78 * dir * scale, 8 * scale, 0, 0, -42 * dir, -10, -42 * dir, 10, 0x365e33).setStrokeStyle(2, dark),scene.add.circle(60 * dir * scale, -7 * scale, 3.6 * scale, 0xffffff),scene.add.rectangle(52 * dir * scale, 10 * scale, 56 * scale, 4 * scale, 0xf0e4c6)]; for (let i = 0; i < 6; i += 1) { parts.push(scene.add.triangle((24 + i * 8) * dir * scale, 9 * scale, -3, 0, 0, 5, 3, 0, 0xf0e4c6)); parts.push(scene.add.triangle((-24 + i * 11) * dir * scale, -8 * scale, 0, 0, -4, -7, 4, -7, 0x284924)); } return parts; }
  static createEagle(scene, dir, scale, c, dark) { return [scene.add.ellipse(0, 8 * scale, 40 * scale, 34 * scale, c).setStrokeStyle(3, dark),scene.add.circle(30 * dir * scale, -10 * scale, 16 * scale, c).setStrokeStyle(3, dark),scene.add.triangle(-10 * dir * scale, -10 * scale, -92 * dir, 20, 0, -20, 30 * dir, 10, 0xc6c5ad).setStrokeStyle(2, dark),scene.add.triangle(4 * dir * scale, -9 * scale, -30 * dir, 10, 0, -18, 92 * dir, 22, 0x939389).setStrokeStyle(2, dark),scene.add.triangle(52 * dir * scale, -10 * scale, 0, 7, 0, -7, 20 * dir, 0, 0xf1d27a).setStrokeStyle(1, dark),scene.add.rectangle(8 * dir * scale, 25 * scale, 3 * scale, 12 * scale, 0xd7a84a),scene.add.rectangle(18 * dir * scale, 25 * scale, 3 * scale, 12 * scale, 0xd7a84a),scene.add.circle(38 * dir * scale, -16 * scale, 3.6 * scale, 0xffffff)]; }
}
